library(ggplot2)
library(rlang)

f=read.table("TCGA_clinical_expression.txt",sep="\t")
dm<-as.matrix(f)
if(nrow(dm)<9){
    png("boxplot_distribution_VHL_mutation_type.png",height=10,width=5,res=100,units='in')
    plot(0)
    dev.off()
}
geneName <- dm[9,1]
dm<-dm[,which(dm[8,]!="Not_available")]

m1F=cbind(dm[9,which(dm[8,]=="Deep_Deletion")])
m2F=cbind(dm[9,which(dm[8,]=="Truncating_Mutation")])
m3F=cbind(dm[9,which(dm[8,]=="Missense_Mutation_putative_driver")])
m4F=cbind(dm[9,which(dm[8,]=="Inframe_Mutation")])
m5F=cbind(dm[9,which(dm[8,]=="Missense_Mutation_putative_passenger")])
m6F=cbind(dm[9,which(dm[8,]=="No_mutation")])


a1<-data.frame(group="Deep deletion",value=log2(as.numeric(m1F)))
b1<-data.frame(group="Truncating mutation",value=log2(as.numeric(m2F)))
c1<-data.frame(group="Missense mutation (putative driver)",value=log2(as.numeric(m3F)))
d1<-data.frame(group="Inframe mutation (putative passenger)",value=log2(as.numeric(m4F)))
e1<-data.frame(group="Missense mutation (putative passenger)",value=log2(as.numeric(m5F)))
f1<-data.frame(group="No mutation",value=log2(as.numeric(m6F)))
df <-rbind(a1,b1,c1,d1,e1,f1)

m1 = length(as.numeric(m1F))
m1_H = sum(as.numeric(m1F)>1.0)
m2 = length(as.numeric(m2F))
m2_H = sum(as.numeric(m2F)>1.0)
m3 = length(as.numeric(m3F))
m3_H = sum(as.numeric(m3F)>1.0)
m4 = length(as.numeric(m4F))
m4_H = sum(as.numeric(m4F)>1.0)
m5 = length(as.numeric(m5F))
m6 = length(as.numeric(m6F))

sum_H=m1_H+m2_H+m3_H+m4_H
sum = length(m1F)+length(m2F)+length(m3F)+length(m4F)
m1_matrix=matrix(c(m1_H,sum_H,m1,sum),2,2)
m2_matrix=matrix(c(m2_H,sum_H,m2,sum),2,2)
m3_matrix=matrix(c(m3_H,sum_H,m3,sum),2,2)
m4_matrix=matrix(c(m4_H,sum_H,m4,sum),2,2)

fisher_m1=paste("p=",format(fisher.test(m1_matrix,alternative="two.sided")$p.value,digits=2),sep="")
fisher_m2=paste("p=",format(fisher.test(m2_matrix)$p.value,digits=2),sep="")
fisher_m3=paste("p=",format(fisher.test(m3_matrix)$p.value,digits=2),sep="")
fisher_m4=paste("p=",format(fisher.test(m4_matrix)$p.value,digits=2))

print(fisher_m1)
print(fisher_m2)
print(fisher_m3)
print(fisher_m4)

#Wilcoxon ranking test
m1<-as.numeric(m1F)
m2<-as.numeric(m2F)
m3<-as.numeric(m3F)
m4<-as.numeric(m4F)

a1<-as.numeric(wilcox.test(m1,c(m2,m3,m4),paired=FALSE)$statistic)
a2<-as.numeric(wilcox.test(m2,c(m1,m3,m4),paired=FALSE)$statistic)
a3<-as.numeric(wilcox.test(m3,c(m1,m2,m4),paired=FALSE)$statistic)
a4<-as.numeric(wilcox.test(m4,c(m1,m2,m3),paired=FALSE)$statistic)



##
a1<-round(as.numeric(wilcox.test(m1,m1,paired=FALSE)$p.value),digits=3)
a2<-round(as.numeric(wilcox.test(m1,m2,paired=FALSE)$p.value),digits=3)
a3<-round(as.numeric(wilcox.test(m1,m3,paired=FALSE)$p.value),digits=3)
a4<-round(as.numeric(wilcox.test(m1,m4,paired=FALSE)$p.value),digits=3)
a5<-round(as.numeric(wilcox.test(m1,m5,paired=FALSE)$p.value),digits=3)
a6<-round(as.numeric(wilcox.test(m1,m6,paired=FALSE)$p.value),digits=3)

b1<-round(as.numeric(wilcox.test(m2,m1,paired=FALSE)$p.value),digits=3)
b2<-round(as.numeric(wilcox.test(m2,m2,paired=FALSE)$p.value),digits=3)
b3<-round(as.numeric(wilcox.test(m2,m3,paired=FALSE)$p.value),digits=3)
b4<-round(as.numeric(wilcox.test(m2,m4,paired=FALSE)$p.value),digits=3)
b5<-round(as.numeric(wilcox.test(m2,m5,paired=FALSE)$p.value),digits=3)
b6<-round(as.numeric(wilcox.test(m2,m6,paired=FALSE)$p.value),digits=3)

c1<-round(as.numeric(wilcox.test(m3,m1,paired=FALSE)$p.value),digits=3)
c2<-round(as.numeric(wilcox.test(m3,m2,paired=FALSE)$p.value),digits=3)
c3<-round(as.numeric(wilcox.test(m3,m3,paired=FALSE)$p.value),digits=3)
c4<-round(as.numeric(wilcox.test(m3,m4,paired=FALSE)$p.value),digits=3)
c5<-round(as.numeric(wilcox.test(m3,m5,paired=FALSE)$p.value),digits=3)
c6<-round(as.numeric(wilcox.test(m3,m6,paired=FALSE)$p.value),digits=3)

d1<-round(as.numeric(wilcox.test(m4,m1,paired=FALSE)$p.value),digits=3)
d2<-round(as.numeric(wilcox.test(m4,m2,paired=FALSE)$p.value),digits=3)
d3<-round(as.numeric(wilcox.test(m4,m3,paired=FALSE)$p.value),digits=3)
d4<-round(as.numeric(wilcox.test(m4,m4,paired=FALSE)$p.value),digits=3)
d5<-round(as.numeric(wilcox.test(m4,m5,paired=FALSE)$p.value),digits=3)
d6<-round(as.numeric(wilcox.test(m4,m6,paired=FALSE)$p.value),digits=3)

e1<-round(as.numeric(wilcox.test(m5,m1,paired=FALSE)$p.value),digits=3)
e2<-round(as.numeric(wilcox.test(m5,m2,paired=FALSE)$p.value),digits=3)
e3<-round(as.numeric(wilcox.test(m5,m3,paired=FALSE)$p.value),digits=3)
e4<-round(as.numeric(wilcox.test(m5,m4,paired=FALSE)$p.value),digits=3)
e5<-round(as.numeric(wilcox.test(m5,m5,paired=FALSE)$p.value),digits=3)
e6<-round(as.numeric(wilcox.test(m5,m6,paired=FALSE)$p.value),digits=3)

f1<-round(as.numeric(wilcox.test(m6,m1,paired=FALSE)$p.value),digits=3)
f2<-round(as.numeric(wilcox.test(m6,m2,paired=FALSE)$p.value),digits=3)
f3<-round(as.numeric(wilcox.test(m6,m3,paired=FALSE)$p.value),digits=3)
f4<-round(as.numeric(wilcox.test(m6,m4,paired=FALSE)$p.value),digits=3)
f5<-round(as.numeric(wilcox.test(m6,m5,paired=FALSE)$p.value),digits=3)
f6<-round(as.numeric(wilcox.test(m6,m6,paired=FALSE)$p.value),digits=3)

print(c("",   "m1","m2","m3","m4","m5","m6"),quote=FALSE)
print(c("m1",   a1,   a2,     a3,    a4,a5,a6),quote=FALSE)
print(c("m2",   b1,   b2,     b3,    b4,b5,b6),quote=FALSE)
print(c("m3",   c1,   c2,     c3,    c4,c5,c6),quote=FALSE)
print(c("m4",   d1,   d2,     d3,    d4,d5,d6),quote=FALSE)
print(c("m5",   e1,   e2,     e3,    e4,e5,e6),quote=FALSE)
print(c("m6",   f1,   f2,     f3,    f4,f5,f6),quote=FALSE)

cat(a1)
cat("\n")
cat(a2)
cat("\n")
cat(a3)
cat("\n")
cat(a4)
cat("\n")
cat(a5)
cat("\n")
cat(a6)
cat("\n")
cat(b1)
cat("\n")
cat(b2)
cat("\n")
cat(b3)
cat("\n")
cat(b4)
cat("\n")
cat(b5)
cat("\n")
cat(b6)
cat("\n")
cat(c1)
cat("\n")
cat(c2)
cat("\n")
cat(c3)
cat("\n")
cat(c4)
cat("\n")
cat(c5)
cat("\n")
cat(c6)
cat("\n")
cat(d1)
cat("\n")
cat(d2)
cat("\n")
cat(d3)
cat("\n")
cat(d4)
cat("\n")
cat(d5)
cat("\n")
cat(d6)
cat("\n")
cat(e1)
cat("\n")
cat(e2)
cat("\n")
cat(e3)
cat("\n")
cat(e4)
cat("\n")
cat(e5)
cat("\n")
cat(e6)
cat("\n")
cat(f1)
cat("\n")
cat(f2)
cat("\n")
cat(f3)
cat("\n")
cat(f4)
cat("\n")
cat(f5)
cat("\n")
cat(f6)
cat("\n")


png("boxplot_distribution_VHL_mutation_type.png",height=10,width=5,res=100,units='in')
ggplot(df,aes(x=group, y=value,fill=group))+stat_boxplot(geom="errorbar",width=0.5)+geom_boxplot(lwd=0.5,color="black",outlier.shape=NA)+geom_jitter(position=position_jitter(width=0.2),size=2,color="black",alpha=1)+labs(x="VHL mutation type",y=paste(geneName," (log2(FPKM))"))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(),panel.border=element_blank(),axis.line=element_line(colour="black",size=1),axis.ticks.x=element_line(size=1,colour="black"),axis.ticks.y=element_line(size=1,colour="black"),axis.text.x=element_text(size=24,face="plain",color="black"),axis.text.y=element_text(size=24,face="plain",color="black"),axis.title.x=element_text(face="plain",size=24,vjust=0.4),axis.title.y=element_text(face="plain",size=24,vjust=0.4),legend.position="none",line=element_line(size=2,colour="black"))+theme(axis.text.x=element_text(angle=65,hjust=1))+theme(plot.margin=unit(c(0.1,0.1,0.01,0.2),"in"))

dev.off()



mut_driver<- c(m1F,m2F,m3F)
mut_passenger <- c(m4F,m5F,m6F)
wilcox.test(as.numeric(mut_driver), as.numeric(mut_passenger), paired=FALSE)





print("!!!!!!!!!!1")
print(round(as.numeric(wilcox.test(c(as.numeric(m1F),as.numeric(m2F),as.numeric(m3F)),c(as.numeric(m4F),as.numeric(m5F),as.numeric(m6F)),paired=FALSE)$p.value),digits=3))



